[package]
name = "entities"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
sea-orm = { version = "1.1.4", features = ["sqlx-sqlite"] }
serde = { version = "1", features = ["derive"] }