[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "6.0.0"
base64 = "0.22.1"
rust-crypto = "0.2.36"
syntect = "5.0"
chrono = "0.4.39"

[dependencies.uuid]
version = "1.12.1"
features = [
    "v4",
    "fast-rng",
    "macro-diagnostics"
]